pipeline:
  name: ServiceOverridePipeline
  identifier: ServiceOverridePipeline
  projectIdentifier: p1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: ServiceOverrideCheck
          environment:
            environmentRef: servOverride2
            gitBranch: main
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infraServiceOverride
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
